# Generated by Django 2.2.16 on 2022-02-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CD',
        ),
    ]
